spring.application.name=organisation-service

server.port=0
spring.zipkin.base-url=http://localhost:9411


eureka.client.service-url.defaultZone=http://localhost:5000/eureka
resilience4j.circuitbreaker.instances.employeeservice.register-health-indicator=true

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always


resilience4j.circuitbreaker.instances.EmployeeService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.EmployeeService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.EmployeeService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.EmployeeService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.EmployeeService.automatic-transition-from-open-to-half-open-enabled=true

spring.cloud.openfeign.circuitbreaker.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0


logging.pattern.level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"
