spring.application.name=OrganisationDetails
server.port=0

server.servlet.context-path=/organisationDetails

eureka.client.service-url.defaultZone=http://localhost:5000/eureka

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

spring.cloud.openfeign.circuitbreaker.enabled=true