spring.application.name=Configuration_Server
server.port=8888
#spring.cloud.config.server.native.search-locations=file:///I:/Miceoservice/centralized
#spring.profiles.active=native

#spring.cloud.config.server.git.uri=file:///I:/Miceoservice/centralized

spring.cloud.config.server.git.uri=https://11A7WSE6A0DbZrUYZhNjpd_lKlSpUfsbfjOI2U9oNu0b1cBnZLQCrwpIQ0IAlzSfexRQWCOVJ3Z0xX6Gah@github.com/shekharpokharkar/Config_Details.git
#spring.cloud.config.server.git.username=shekharpokharkar
#spring.cloud.config.server.git.password=11A7WSE6A0DbZrUYZhNjpd_lKlSpUfsbfjOI2U9oNu0b1cBnZLQCrwpIQ0IAlzSfexRQWCOVJ3Z0xX6Gah
spring.cloud.config.server.git.default-label=main
spring.profiles.active=git

#spring.datasource.url=jdbc:mysql://localhost:3306/seleniumexpress_microservice
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.profiles.active=jdbc
#spring.cloud.config.server.jdbc.sql=SELECT application_Key,value FROM properties where APPLICATION =? and PROFILE=? and LABEL=?

# Enable encryption with symmetric key
spring.cloud.config.server.encrypt.enabled=true
encrypt.key=Abhilash!123@#@456

eureka.client.service-url.defaultZone=http://localhost:5000/eureka
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id==Config_Server

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=config-group
spring.kafka.consumer.auto-offset-reset=earliest

# Enable bus refresh endpoint
management.endpoints.web.exposure.include=busrefresh
management.endpoint.health.show-details=always
