spring.application.name=Star-Employee
#spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev

#spring.cloud.config.label=latest

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://localhost:5000/eureka
spring.config.import=optional:configserver:
spring.cloud.config.enabled=true
spring.cloud.config.discovery.service-id=Configuration_Server
